#!/usr/bin/env python3
# -*- coding:utf8 -*-
import sys
from question.wh_question import WhQuestion
from question.yes_no_question import YesNoQuestion

class Ask:
    def __init__(self, article, n):
        self.n = n
        self.questions = []
        article = open(article).read()
        self.paragraphs = [s.strip() for s in article.splitlines()]
    
    def generate(self):
        yesno = YesNoQuestion(self.paragraphs, self.n)
        yesno.ask()
        self.questions.extend(yesno.questions)

        wh = WhQuestion(self.paragraphs, self.n)
        wh.ask()
        self.questions.extend(wh.questions)

        self.rank_and_print_questions()
    
    def rank_and_print_questions(self):
        # TODO: rank questions before printing
        for i in range(0, self.n):
            if i >= len(self.questions):
                print("No more question")
            else:
                print(self.questions[i])
    
if __name__ == '__main__':
    article = sys.argv[1]
    n = int(sys.argv[2])
    ask = Ask(article, n)
    ask.generate()