#!/usr/bin/env python3
# -*- coding:utf8 -*-
import sys
from processor.stanza_process import StanzaProcessor
from question.wh_question import WhQuestion
from question.yes_no_question import YesNoQuestion
import random
class Ask:
    def __init__(self, article, n):
        self.n = n
        self.questions = []
        self.processor = StanzaProcessor(article=article)
        self.processor.process()
    
    def generate(self):
        yesno = YesNoQuestion(self.processor.processed_article)
        wh = WhQuestion(self.processor.processed_article)
        yesno.ask()
        wh.ask(self.n)
        self.questions.extend(yesno.questions)
        self.questions.extend(wh.questions)

        self.rank_questions()
        
        for i in range(0, self.n):
            if i >= len(self.questions):
                print("No more question")
            else:
                print(self.questions[i])
    
    def rank_questions(self):
        random.shuffle(self.questions)
        # TODO: rank questions before printing
        return
    
if __name__ == '__main__':
    article = sys.argv[1]
    n = int(sys.argv[2])
    ask = Ask(article, n)
    ask.generate()